"""Add location and asset models

Revision ID: 2d1199537248
Revises: 244449d19038
Create Date: 2026-06-10 08:58:32.790380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1199537248'
down_revision: Union[str, Sequence[str], None] = '244449d19038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assetcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assetcategory_id'), 'assetcategory', ['id'], unique=False)
    op.create_index(op.f('ix_assetcategory_name'), 'assetcategory', ['name'], unique=True)
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_id'), 'site', ['id'], unique=False)
    op.create_index(op.f('ix_site_name'), 'site', ['name'], unique=False)
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_building_id'), 'building', ['id'], unique=False)
    op.create_index(op.f('ix_building_name'), 'building', ['name'], unique=False)
    op.create_table('floor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_floor_id'), 'floor', ['id'], unique=False)
    op.create_index(op.f('ix_floor_name'), 'floor', ['name'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('floor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['floor_id'], ['floor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_id'), 'room', ['id'], unique=False)
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('height_u', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('depth_mm', sa.Float(), nullable=True),
    sa.Column('power_capacity_kw', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rack_id'), 'rack', ['id'], unique=False)
    op.create_index(op.f('ix_rack_name'), 'rack', ['name'], unique=False)
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_tag', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('warranty_start', sa.Date(), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('rack_id', sa.Integer(), nullable=True),
    sa.Column('u_position', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['assetcategory.id'], ),
    sa.ForeignKeyConstraint(['rack_id'], ['rack.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_asset_tag'), 'asset', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_asset_hostname'), 'asset', ['hostname'], unique=False)
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_index(op.f('ix_asset_serial_number'), 'asset', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_serial_number'), table_name='asset')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_index(op.f('ix_asset_hostname'), table_name='asset')
    op.drop_index(op.f('ix_asset_asset_tag'), table_name='asset')
    op.drop_table('asset')
    op.drop_index(op.f('ix_rack_name'), table_name='rack')
    op.drop_index(op.f('ix_rack_id'), table_name='rack')
    op.drop_table('rack')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_index(op.f('ix_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_floor_name'), table_name='floor')
    op.drop_index(op.f('ix_floor_id'), table_name='floor')
    op.drop_table('floor')
    op.drop_index(op.f('ix_building_name'), table_name='building')
    op.drop_index(op.f('ix_building_id'), table_name='building')
    op.drop_table('building')
    op.drop_index(op.f('ix_site_name'), table_name='site')
    op.drop_index(op.f('ix_site_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_assetcategory_name'), table_name='assetcategory')
    op.drop_index(op.f('ix_assetcategory_id'), table_name='assetcategory')
    op.drop_table('assetcategory')
    # ### end Alembic commands ###
